unique_ids:
  forms:
    Create_Simulation: CG4ZEIW63P7WQHVHTSKG4YYHY6DIYPRQ
    Train_Model: F4JOGNQP7Z5UYBIGYRIUS6DJ63TOMNEU
    Display_Simulation: DPEU6EXQ43VHXYNMEPWH5GMXNQ67WC5W
    Display_Model_Prediction: 4JHJYWRCTJKXXQWSRE45KYHI5XTV3KAT
    Sidebar: XZTKFM6PEZCYWNFWI3ASG3Y6H4TKZPIF
  modules: {}
  server_modules:
    ServerModule1: QGGHBSIDBY4MRQ7XF7EOHECBLTO7WDI3
  assets:
    dashboard.html: A6ITFXTR7RFTWCZUC6S5OGDZGMVSNHOE
    single-column.html: 6XSJ7CZSON6TYZTWJKJ7OI3V2T4LGHCS
    theme.css: UEFZI2GKNWRYHEAAQTBWWURC7FMBS25Q
