unique_ids:
  forms:
    Create_Simulation: CG4ZEIW63P7WQHVHTSKG4YYHY6DIYPRQ
    Sidebar: XZTKFM6PEZCYWNFWI3ASG3Y6H4TKZPIF
    Train_Model: F4JOGNQP7Z5UYBIGYRIUS6DJ63TOMNEU
  modules: {}
  server_modules: {}
  assets:
    dashboard.html: A6ITFXTR7RFTWCZUC6S5OGDZGMVSNHOE
    single-column.html: 6XSJ7CZSON6TYZTWJKJ7OI3V2T4LGHCS
    theme.css: UEFZI2GKNWRYHEAAQTBWWURC7FMBS25Q
